create database CLOTHCENTRE;
USE CLOTHCENTRE;
create table CLOTHCENTRE_DETAILS(
SHOP_ID BIGINT(20),
SHOP_NAME VARCHAR(40) UNIQUE,
SHOP_LOCATION VARCHAR(25),
SHOP_GSTNO VARCHAR(15),
SHOP_CONTACTNO INT(10),
primary key(SHOP_ID)
);
SELECT*FROM CLOTHCENTRE_DETAILS;
DESC CLOTHCENTRE_DETAILS;

alter table CLOTHCENTRE_DETAILS modify SHOP_GSTNO VARCHAR(15) unique;
alter table CLOTHCENTRE_DETAILS modify SHOP_CONTACTNO BIGINT;

create table OWNER_DETAILS(
OWNER_NAME VARCHAR(15),
OWNER_PHONENO INT(10),
OWNER_AGE TINYINT(100)
);

SELECT*FROM clothcentre.OWNER_DETAILS;
DESC OWNER_DETAILS;
alter table OWNER_DETAILS modify OWNER_AGE TINYINT CHECK(AGE>20);
alter table OWNER_DETAILS modify OWNER_PHONENO BIGINT;

INSERT INTO clothcentre.CLOTHCENTRE_DETAILS(SHOP_ID, SHOP_NAME, SHOP_LOCATION, SHOP_GSTNO, SHOP_CONTACTNO)VALUES(123,'NAMDE STYLE','TIPTUR','123NST444',6361622695);
INSERT INTO clothcentre.CLOTHCENTRE_DETAILS VALUES(222,'CLASSIC POLO','TUMAKUR','222CPT111',9964920489);
INSERT INTO clothcentre.CLOTHCENTRE_DETAILS VALUES(333,' POLO ','VIJAYANAGAR','33PLO222',8861055268);
INSERT INTO clothcentre.CLOTHCENTRE_DETAILS VALUES(444,'STYLE ZONE','YELHANKA','444SEZ33',8277242581);
INSERT INTO clothcentre.CLOTHCENTRE_DETAILS VALUES(555,' TARANGA','MARATHALLI','555TAG444',8183015329);
SELECT*FROM CLOTHCENTRE_DETAILS;

INSERT INTO clothcentre.OWNER_DETAILS(OWNER_NAME, OWNER_PHONENO, OWNER_AGE)VALUES('NIJGUNA',8970754032,27);
INSERT INTO clothcentre.OWNER_DETAILS(OWNER_NAME, OWNER_PHONENO, OWNER_AGE) VALUES('SUBASH',6363457812,35);
INSERT INTO clothcentre.OWNER_DETAILS(OWNER_NAME, OWNER_PHONENO, OWNER_AGE) VALUES('LOHITH',8812467923,31);
INSERT INTO clothcentre.OWNER_DETAILS(OWNER_NAME, OWNER_PHONENO, OWNER_AGE) VALUES('APPU',7256489516,24);
INSERT INTO clothcentre.OWNER_DETAILS(OWNER_NAME, OWNER_PHONENO, OWNER_AGE) VALUES('DARSHAN', 9912783622,23);
INSERT INTO clothcentre.OWNER_DETAILS(OWNER_NAME, OWNER_PHONENO, OWNER_AGE) VALUES('THEERTHA',9742711220,23);

alter table clothcentre.CLOTHCENTRE_DETAILS add SHOP_INCOME BIGINT;
update clothcentre.CLOTHCENTRE_DETAILS SET SHOP_INCOME =200000 where SHOP_ID =123;
update clothcentre.CLOTHCENTRE_DETAILS SET SHOP_INCOME =100000 where SHOP_ID =222;
update clothcentre.CLOTHCENTRE_DETAILS SET SHOP_INCOME =75000 where SHOP_ID =333;
update clothcentre.CLOTHCENTRE_DETAILS SET SHOP_INCOME =80000 where SHOP_ID =444;
update clothcentre.CLOTHCENTRE_DETAILS SET SHOP_INCOME =65000 where SHOP_ID =555;

-- MIN,MAX,SUM,AVG,COUNT--
select MIN(SHOP_INCOME) from clothcentre.CLOTHCENTRE_DETAILS;
select MIN(SHOP_INCOME)AS SHOP_MINVALUE from clothcentre.CLOTHCENTRE_DETAILS;

select MAX(SHOP_INCOME) from clothcentre.CLOTHCENTRE_DETAILS;
select MIN(SHOP_INCOME)AS SHOP_MAXVALUE from clothcentre.CLOTHCENTRE_DETAILS;

select SUM(SHOP_INCOME) from clothcentre.CLOTHCENTRE_DETAILS;
select SUM(SHOP_INCOME)AS SUM_SHOPVALUE from clothcentre.CLOTHCENTRE_DETAILS;

select AVG(SHOP_INCOME) from clothcentre.CLOTHCENTRE_DETAILS;
select AVG(SHOP_INCOME)AS SHOP_AVGVALUE from clothcentre.CLOTHCENTRE_DETAILS;

select COUNT(OWNER_NAME) from clothcentre.OWNER_DETAILS;
select COUNT(OWNER_NAME)AS NAME_COUNT from clothcentre.OWNER_DETAILS;

select S.SHOP_ID,SHOP_NAME from clothcentre.CLOTHCENTRE_DETAILS AS S;

-- ASC OR DESC--
select*FROM clothcentre.CLOTHCENTRE_DETAILS order by SHOP_ID DESC; 
select*from clothcentre.CLOTHCENTRE_DETAILS order by SHOP_INCOME ASC;


-- IN AND BETWEEN--
select*from clothcentre.CLOTHCENTRE_DETAILS where SHOP_NAME IN('CLASSIC POLO','STYLE ZONE');
SELECT*FROM clothcentre.CLOTHCENTRE_DETAILS where SHOP_ID IN(123,555,444);

SELECT *FROM clothcentre.OWNER_DETAILS WHERE OWNER_NAME BETWEEN'APPU'AND'THEERTHA';
SELECT *FROM clothcentre.CLOTHCENTRE_DETAILS WHERE SHOP_ID BETWEEN 333 AND 555;

-- WILDCARD OPERATORS--
SELECT*FROM clothcentre.CLOTHCENTRE_DETAILS WHERE SHOP_NAME LIKE 'C%';
SELECT*FROM clothcentre.CLOTHCENTRE_DETAILS WHERE SHOP_NAME LIKE 'N%D%';
SELECT*FROM clothcentre.CLOTHCENTRE_DETAILS WHERE SHOP_LOCATION LIKE 'T%R';
SELECT*FROM clothcentre.CLOTHCENTRE_DETAILS WHERE SHOP_LOCATION LIKE '_I%R';
SELECT*FROM clothcentre.OWNER_DETAILS WHERE OWNER_NAME LIKE '__%A';
SELECT*FROM clothcentre.CLOTHCENTRE_DETAILS WHERE SHOP_LOCATION LIKE '___A%R';

-- DELETE--
DELETE FROM clothcentre.OWNER_DETAILS WHERE OWNER_NAME ='SUBASH';
SELECT*FROM clothcentre.OWNER_DETAILS;

-- TRUNCATE--
truncate table owner_details;
SELECT*FROM clothcentre.OWNER_DETAILS;

drop table owner_details;















